const Mpa = [
  {
    id: 1,
    image: "/images/usmandar.jpg",
    name: "Usman Dar",
    party: "PTI",
    logo: "/images/ptilogo.png",
    area: "NA-52",
    city: "sialkot",
  },
  {
    id: 2,
    image: "/images/khwajaAsif.jpg",
    name: "Khawaja Asif",
    party: "PLMN",
    logo: "/images/plmn.png",
    area: "NA-52",
    city: "sialkot",
  },
  {
    id: 3,
    image: "/images/qarisamar.png",
    name: "Mufti Samar Abbas Attari",
    party: "TLP",
    logo: "/images/tlp.png",
    area: "NA-52",
    city: "sialkot",
  },
  {
    id: 4,
    image: "/images/raza.jpeg",
    name: "Mr Raza Rabani Khan",
    party: "PPP",
    logo: "/images/ppp.png",
    area: "NA-52",
    city: "sialkot",
  },
  {
    id: 5,
    image: "/images/ahsan.png",
    name: "Ahsan Saleem",
    party: "PTI",
    logo: "/images/ptilogo.png",
    area: "NA-52",
    city: "rawalpindi",
  },
  {
    id: 6,
    image: "/images/pp63.jpg",
    name: "Chouhdary Muhammad Iqbal",
    party: "PLMN",
    logo: "/images/plmn.png",
    area: "NA-52",
    city: "rawalpindi",
  },
  {
    id: 7,
    image: "/images/abidppp.jpeg",
    name: "Mr Abid Hussain",
    party: "PPP",
    logo: "/images/ppp.png",
    area: "NA-52",
    city: "rawalpindi",
  },
  {
    id: 8,
    image: "/images/kashif.jpg",
    name: "Hafiz Kashif Aasi",
    party: "TLP",
    logo: "/images/tlp.png",
    area: "NA-52",
    city: "rawalpindi",
  },
  {
    id: 9,
    image: "/images/abdul.jpg",
    name: "Abdul Haye Dasti",
    party: "PTI",
    logo: "/images/ptilogo.png",
    area: "NA-52",
    city: "gujranwala",
  },
  {
    id: 10,
    image: "/images/pp59.jpg",
    name: "Waqar Ahmed",
    party: "PLMN",
    logo: "/images/plmn.png",
    area: "NA-52",
    city: "gujranwala",
  },
  {
    id: 11,
    image: "/images/syedamin.jpeg",
    name: "Syed Amin",
    party: "PPP",
    logo: "/images/ppp.png",
    area: "NA-52",
    city: "gujranwala",
  },
  {
    id: 12,
    image: "/images/usmantlp.jpeg",
    name: "Usama Akhtar",
    party: "TLP",
    logo: "/images/tlp.png",
    area: "NA-52",
    city: "gujranwala",
  },
  {
    id: 13,
    image: "/images/aliakhtar.jpg",
    name: "Ali Akhtar",
    party: "PTI",
    logo: "/images/ptilogo.png",
    area: "NA-52",
    city: "lahore",
  },
  {
    id: 14,
    image: "/images/w353.jpg",
    name: "Ms Bushra Butt",
    party: "PLMN",
    logo: "/images/plmn.png",
    area: "NA-52",
    city: "lahore",
  },
  {
    id: 15,
    image: "/images/rana.jpg",
    name: "Rana Shamshad",
    party: "PPP",
    logo: "/images/ppp.png",
    area: "NA-52",
    city: "lahore",
  },
  {
    id: 16,
    image: "/images/mufti.jpeg",
    name: "Mufti Muneeb",
    party: "TLP",
    logo: "/images/tlp.png",
    area: "NA-52",
    city: "lahore",
  },
];
export default Mpa;
