const Rows = [
  {
    id: 1,
    image: "/images/ali.jpg",
    name: "Ali Muhammad Khan",
    party: "PTI",
    logo: "/images/ptilogo.png",
    area: "NA-52",
    city: "sialkot",
  },
  {
    id: 2,
    image: "/images/78.jpg",
    name: "Ahsan Iqbal",
    party: "PLMN",
    logo: "/images/plmn.png",
    area: "NA-52",
    city: "sialkot",
  },
  {
    id: 3,
    image: "/images/ehtisam.jpeg",
    name: "Ehtisham Raza",
    party: "PPP",
    logo: "/images/ppp.png",
    area: "NA-52",
    city: "sialkot",
  },
  {
    id: 4,
    image: "/images/pp62.jpg",
    name: "Chouhdary Awan",
    party: "TLP",
    logo: "/images/tlp.png",
    area: "NA-52",
    city: "sialkot",
  },
  {
    id: 5,
    image: "/images/Murad.jpg",
    name: "Murad Saeed",
    party: "PTI",
    logo: "/images/ptilogo.png",
    area: "NA-52",
    city: "rawalpindi",
  },
  {
    id: 6,
    image: "/images/sajid.jpeg",
    name: "Muhammad Sajjad",
    party: "PLMN",
    logo: "/images/plmn.png",
    area: "NA-52",
    city: "rawalpindi",
  },
  {
    id: 7,
    image: "/images/raja.jpeg",
    name: "Raja Perviaz Ashraf",
    party: "PPP",
    logo: "/images/ppp.png",
    area: "NA-52",
    city: "rawalpindi",
  },
  {
    id: 8,
    image: "/images/saad.jpg",
    name: "Saad Rizvi",
    party: "TLP",
    logo: "/images/tlp.png",
    area: "NA-52",
    city: "rawalpindi",
  },
  {
    id: 9,
    image: "/images/aliafzal.png",
    name: "Ali Afzal",
    party: "PTI",
    logo: "/images/ptilogo.png",
    area: "NA-52",
    city: "gujranwala",
  },
  {
    id: 10,
    image: "/images/rana.jpg",
    name: "Rana Shameem",
    party: "PLMN",
    logo: "/images/plmn.png",
    area: "NA-52",
    city: "gujranwala",
  },
  {
    id: 11,
    image: "/images/irshad.jpeg",
    name: "Mian Irshad",
    party: "PPP",
    logo: "/images/ppp.png",
    area: "NA-52",
    city: "gujranwala",
  },
  {
    id: 12,
    image: "/images/khalid.jpeg",
    name: "Khalid",
    party: "TLP",
    logo: "/images/tlp.png",
    area: "NA-52",
    city: "gujranwala",
  },
  {
    id: 13,
    image: "/images/imran.jpg",
    name: "Imran Khan",
    party: "PTI",
    logo: "/images/ptilogo.png",
    area: "NA-52",
    city: "lahore",
  },
  {
    id: 14,
    image: "/images/shahbaz.jpg",
    name: "Shahbaz Sharif",
    party: "PLMN",
    logo: "/images/plmn.png",
    area: "NA-52",
    city: "lahore",
  },
  {
    id: 15,
    image: "/images/bilawal.jpeg",
    name: "Bilawal Bhuto Zardari",
    party: "PPP",
    logo: "/images/ppp.png",
    area: "NA-52",
    city: "lahore",
  },
  {
    id: 16,
    image: "/images/engr.jpeg",
    name: "Engineer Rizwan",
    party: "TLP",
    logo: "/images/tlp.png",
    area: "NA-52",
    city: "lahore",
  },
];
export default Rows;
