const Rows = [
  {
    id: 1,
    image: "/images/ali.jpg",
    name: "Ali Muhammad Khan",
    party: "PTI",
    logo: "/images/ptilogo.png",
    area: "NA-52",
    city: "sialkot",
  },
  {
    id: 2,
    image: "/images/usmandar.jpg",
    name: "Usman Dar",
    party: "PTI",
    logo: "/images/ptilogo.png",
    area: "NA-52",
    city: "sialkot",
  },
  {
    id: 3,
    image: "/images/usmandar.jpg",
    name: "Ali Muhammad Khan",
    party: "PTI",
    logo: "/images/ptilogo.png",
    area: "NA-52",
    city: "lahore",
  },
  {
    id: 4,
    image: "/images/usmandar.jpg",
    name: "Ali Muhammad Khan",
    party: "PTI",
    logo: "/images/ptilogo.png",
    area: "NA-52",
    city: "bahawalpur",
  },
  {
    id: 5,
    image: "/images/usmandar.jpg",
    name: "Ali Muhammad Khan",
    party: "PTI",
    logo: "/images/ptilogo.png",
    area: "NA-52",
    city: "sargodha",
  },
  {
    id: 6,
    image: "/images/usmandar.jpg",
    name: "sargodha",
    party: "PTI",
    logo: "/images/ptilogo.png",
    area: "NA-52",
    city: "rawalpindi",
  },
  {
    id: 7,
    image: "/images/usmandar.jpg",
    name: "Gujranwala",
    party: "PTI",
    logo: "/images/ptilogo.png",
    area: "NA-52",
    city: "multan",
  },
  {
    id: 8,
    image: "/images/usmandar.jpg",
    name: "Rawalpindi",
    party: "PTI",
    logo: "/images/ptilogo.png",
    area: "NA-52",
    city: "faisalabad",
  },
  {
    id: 9,
    image: "/images/usmandar.jpg",
    name: "Bahawalpur",
    party: "PTI",
    logo: "/images/ptilogo.png",
    area: "NA-52",
    city: "gujranwala",
  },
];
export default Rows;
